#!/bin/bash -l
#SBATCH --account env540
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --partition=gpu
#SBATCH --qos=gpu
#SBATCH --gres=gpu:1
#SBATCH --time=03:00:00

# Load modules
module load gcc python

# Activate virtual environment or conda environment
source ~/ipeo_venv/bin/activate # Replace with your environment setup

# Run your Python script
python canopyv2.py # Replace with your script name